name: Snyk Container Test
description: ''

inputs:
  snyk_token:
    description: "Snyk authentication token"
    required: true
  image_name:
    description: "Docker image name, eg ghcr.io/cyber-dojo/saver:9a88d8f"
    required: true
  policy_path:
    description: "The filename for the snyk --policy-path, eg .snyk"
    required: false
    default: ".snyk"
  sarif_filename:
    description: "The filename to create in the snyk-test and upload in the kosli-assert"
    required: false
    default: "snyk.container.scan.json"
  kosli_cli_version:
    description: "Version of Kosli CLI, eg 2.11.43"
    required: true
  attestation_name:
    description: "Value for: kosli-attest-snyk --name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - name: Load image from registry
      uses: cyber-dojo/load-image-from-registry@main
      with:
        image_name: "${{ inputs.image_name }}"

    - name: Setup Snyk CLI
      uses: snyk/actions/setup@master
      with:
        snyk-version: v1.1300.2        

    - uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Run Snyk container scan
      shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk_token }}
      run:
        snyk container test "${{ inputs.image_name }}"
          --policy-path="${{ inputs.policy_path }}"
          --sarif
          --sarif-file-output="${{ inputs.sarif_filename }}"

    - name: Setup Kosli CLI
      if:
        ${{ github.ref == 'refs/heads/main' && (success() || failure()) }}
      uses: kosli-dev/setup-cli-action@v3
      with:
        version: ${{ inputs.kosli_cli_version }}

    - name: Attest evidence to Kosli
      shell: bash
      if:
        ${{ github.ref == 'refs/heads/main' && (success() || failure()) }}
      run:
        kosli attest snyk "${{ inputs.image_name }}"
          --artifact-type=docker
          --attachments="${{ inputs.policy_path }}"
          --name="${{ inputs.attestation_name }}"
          --scan-results="${{ inputs.sarif_filename }}"
