name: Snyk Container Test
description: ''

inputs:
  SNYK_TOKEN:
    description: "Snyk authentication token"
    required: true
  IMAGE_NAME:
    description: "Docker image name, eg ghcr.io/cyber-dojo/saver:9a88d8f"
    required: true
  KOSLI_CLI_VERSION:
    description: "Version of Kosli CLI, eg 2.11.43"
    required: true
  attestation_name:
    description: "Value for: kosli-attest-snyk --name"
    required: true

runs:
  using: "composite"
  env:
    SARIF_FILENAME: snyk.container.scan.json
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - name: Load image from registry
      uses: cyber-dojo/load-image-from-registry@main

    - name: Setup Snyk CLI
      uses: snyk/actions/setup@master
      with:
        snyk-version: v1.1300.2        

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Run Snyk container scan
      shell: bash
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run:
        snyk container test "${IMAGE_NAME}"
          --policy-path=.snyk
          --sarif
          --sarif-file-output="${SARIF_FILENAME}"

    - name: Setup Kosli CLI
      if: ${{ github.ref == 'refs/heads/main' && (success() || failure()) }}
      uses: kosli-dev/setup-cli-action@v2
      with:
        version: ${{ inputs.KOSLI_CLI_VERSION }}

    - name: Attest evidence to Kosli
      shell: bash
      if: ${{ github.ref == 'refs/heads/main' && (success() || failure()) }}
      run:
        kosli attest snyk "${IMAGE_NAME}"
          --artifact-type=oci
          --attachments=.snyk
          --name="${{ inputs.attestation_name }}"
          --scan-results="${SARIF_FILENAME}"
